apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yuzdanyuz
  namespace: argocd
spec:
  description: YuzDanYuz Milliy Sertifikat — Django backend stack
  sourceRepos:
    - https://github.com/menarzullayev/yuzdanyuz-monorepo.git
  destinations:
    - namespace: 'yuzdanyuz-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
