# Generated by Django 5.2.14 on 2026-05-14 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='imports/%Y/%m/%d/', verbose_name='Asl fayl')),
                ('file_type', models.CharField(help_text='docx, xlsx, etc.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Tahlil qilinmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('processed_questions', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, null=True, verbose_name='Xatoliklar jurnali')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Import paketi',
                'verbose_name_plural': 'Import paketlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SC', 'Yagona tanlov (MCQ)'), ('MC', "Ko'p tanlov"), ('MT', 'Moslashtirish'), ('OR', 'Ketma-ketlik'), ('FB', "Bo'shliqni to'ldirish"), ('OE', 'Ochiq savol (Essay)'), ('FU', 'Fayl yuklash')], default='SC', max_length=5)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('initial_difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=20)),
                ('difficulty_index', models.FloatField(default=0.0, help_text='IRT Difficulty Index (b)')),
                ('discrimination_index', models.FloatField(default=1.0, help_text='IRT Discrimination Index (a)')),
                ('language', models.CharField(default='uz', max_length=10)),
                ('shuffling_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
                ('parent_question', models.ForeignKey(blank=True, help_text="Asosiy tildagi savol bilan bog'lash", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='catalog.question')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Bank nomi')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text="Public bank: platform admini tomonidan barcha tenantlarga ko'rinadi")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
                ('questions', models.ManyToManyField(blank=True, related_name='banks', to='catalog.question')),
            ],
            options={
                'verbose_name': 'Savol banki',
                'verbose_name_plural': 'Savol banklari',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Fan nomi')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subjects/icons/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalog.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='catalog.tag'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.topic', verbose_name='Yuqori mavzu')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='catalog.subject')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text="AI yoki Parserdan olingan xomaki ma'lumot")),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('SC', 'Yagona tanlov (MCQ)'), ('MC', "Ko'p tanlov"), ('MT', 'Moslashtirish'), ('OR', 'Ketma-ketlik'), ('FB', "Bo'shliqni to'ldirish"), ('OE', 'Ochiq savol (Essay)'), ('FU', 'Fayl yuklash')], max_length=5, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='catalog.importbatch')),
                ('published_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_source', to='catalog.question')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.topic')),
            ],
            options={
                'verbose_name': 'Qoralama savol',
                'verbose_name_plural': 'Qoralama savollar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='catalog.topic'),
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.JSONField(verbose_name='Savol matni va media')),
                ('options', models.JSONField(verbose_name='Variantlar va javoblar mantiqi')),
                ('explanation', models.JSONField(blank=True, null=True, verbose_name='Yechim izohi')),
                ('adaptive_feedback', models.JSONField(blank=True, null=True, verbose_name='Moslashuvchan qayta aloqa')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Vaqt limiti va boshqa qoidalar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.question')),
            ],
            options={
                'verbose_name': 'Savol versiyasi',
                'verbose_name_plural': 'Savol versiyalari',
                'ordering': ['-version_number'],
                'unique_together': {('question', 'version_number')},
            },
        ),
    ]
