# Generated by Django 5.2.14 on 2026-05-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: 'Asosiy Claude', 'Zaxira Ollama'", max_length=100, verbose_name='Nom')),
                ('provider', models.CharField(choices=[('claude', 'Anthropic Claude'), ('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini'), ('ollama', 'Ollama (Mahalliy / Bepul)')], max_length=20, verbose_name='Provayder')),
                ('model', models.CharField(help_text='claude-sonnet-4-6 | gpt-4o | gemini-1.5-pro | llama3', max_length=100, verbose_name='Model nomi')),
                ('api_key', models.CharField(blank=True, help_text="Ollama uchun bo'sh qoldiring", max_length=500, verbose_name='API kalit')),
                ('base_url', models.CharField(blank=True, help_text='Faqat Ollama uchun: http://localhost:11434', max_length=500, verbose_name='Base URL')),
                ('use_for', models.CharField(choices=[('parser', 'Savol Parseri (Bulk Import)'), ('tutor', 'AI Tutor (Diagnostika)'), ('all', 'Barchasi')], default='all', max_length=20, verbose_name='Foydalanish maqsadi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text="Kichik son = yuqori ustuvorlik. Xato bo'lsa keyingisi urinadi.", verbose_name='Ustuvorlik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider konfiguratsiyasi',
                'verbose_name_plural': 'AI Provider konfiguratsiyalari',
                'ordering': ['priority'],
            },
        ),
    ]
