# Generated by Django 5.2.14 on 2026-05-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionversion',
            name='is_quarantined',
            field=models.BooleanField(db_index=True, default=False, help_text="True bo'lsa, savol yangi exam'larga qo'shilmaydi va affected attempt'lar bonus oladi.", verbose_name='Karantinda'),
        ),
    ]
