# Generated by Django 5.2.14 on 2026-05-16 11:11

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_question_created_by_question_updated_by'),
        ('organizations', '0003_historicalmembership_historicalorganization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalQuestion',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('SC', 'Yagona tanlov (MCQ)'), ('MC', "Ko'p tanlov"), ('MT', 'Moslashtirish'), ('OR', 'Ketma-ketlik'), ('FB', "Bo'shliqni to'ldirish"), ('OE', 'Ochiq savol (Essay)'), ('FU', 'Fayl yuklash')], default='SC', max_length=5)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('initial_difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=20)),
                ('difficulty_index', models.FloatField(default=0.0, help_text='IRT Difficulty Index (b)')),
                ('discrimination_index', models.FloatField(default=1.0, help_text='IRT Discrimination Index (a)')),
                ('language', models.CharField(default='uz', max_length=10)),
                ('shuffling_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Tashkilot')),
                ('parent_question', models.ForeignKey(blank=True, db_constraint=False, help_text="Asosiy tildagi savol bilan bog'lash", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.question')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.subject')),
                ('topic', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.topic')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Savol',
                'verbose_name_plural': 'historical Savollar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
