# Generated by Django 5.2.14 on 2026-05-14 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('org_type', models.CharField(choices=[('platform', 'Platforma'), ('tenant', "O'quv markazi"), ('branch', 'Filial')], default='tenant', max_length=20, verbose_name='Tur')),
                ('status', models.CharField(choices=[('pending', 'Tasdiqlash kutilmoqda'), ('trial', 'Sinov davri'), ('active', 'Faol'), ('suspended', "To'xtatilgan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('tier', models.CharField(choices=[('free', 'Bepul'), ('basic', 'Asosiy'), ('pro', 'Professional'), ('enterprise', 'Korporativ')], default='free', max_length=20, verbose_name='Tarif')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinov tugash vaqti')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='orgs/logos/')),
                ('primary_color', models.CharField(default='#1A73E8', max_length=7, verbose_name='Asosiy rang')),
                ('subdomain', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Sozlamalar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orgs', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organization', verbose_name='Yuqori tashkilot')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Kod nomi')),
                ('display_name', models.CharField(max_length=100, verbose_name="Ko'rinadigan nomi")),
                ('permissions', models.JSONField(default=list, verbose_name='Ruxsatlar')),
                ('is_system_role', models.BooleanField(default=False, help_text="Tizimiy rollar o'chirib bo'lmaydi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OrgInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organizations.orgrole')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('invited', 'Taklif yuborilgan'), ('suspended', "To'xtatilgan"), ('left', 'Chiqib ketgan')], default='invited', max_length=20)),
                ('joined_via', models.CharField(choices=[('manual', "Admin qo'shdi"), ('invite', 'Invite link'), ('api', 'API integratsiya')], default='manual', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Foydalanuvchining asosiy tashkiloti')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.orgrole', verbose_name='Rol')),
            ],
            options={
                'verbose_name': "A'zolik",
                'verbose_name_plural': "A'zoliklar",
                'ordering': ['-created_at'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
