# Generated by Django 5.2.14 on 2026-05-16 11:11

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_single_device_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMembership',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('invited', 'Taklif yuborilgan'), ('suspended', "To'xtatilgan"), ('left', 'Chiqib ketgan')], default='invited', max_length=20)),
                ('joined_via', models.CharField(choices=[('manual', "Admin qo'shdi"), ('invite', 'Invite link'), ('api', 'API integratsiya')], default='manual', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Foydalanuvchining asosiy tashkiloti')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.orgrole', verbose_name='Rol')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical A'zolik",
                'verbose_name_plural': "historical A'zoliklar",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('org_type', models.CharField(choices=[('platform', 'Platforma'), ('tenant', "O'quv markazi"), ('branch', 'Filial')], default='tenant', max_length=20, verbose_name='Tur')),
                ('status', models.CharField(choices=[('pending', 'Tasdiqlash kutilmoqda'), ('trial', 'Sinov davri'), ('active', 'Faol'), ('suspended', "To'xtatilgan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('tier', models.CharField(choices=[('free', 'Bepul'), ('basic', 'Asosiy'), ('pro', 'Professional'), ('enterprise', 'Korporativ')], default='free', max_length=20, verbose_name='Tarif')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinov tugash vaqti')),
                ('logo', models.TextField(blank=True, max_length=100, null=True)),
                ('primary_color', models.CharField(default='#1A73E8', max_length=7, verbose_name='Asosiy rang')),
                ('subdomain', models.SlugField(blank=True, max_length=100, null=True)),
                ('custom_domain', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('single_device_policy', models.BooleanField(default=True, help_text='True: 1 ta qurilma faol, yangi kirsa eski sessiya uzilib qoladi', verbose_name='Bir qurilma siyosati')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Sozlamalar')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Yuqori tashkilot')),
            ],
            options={
                'verbose_name': 'historical Tashkilot',
                'verbose_name_plural': 'historical Tashkilotlar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrgRole',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='Kod nomi')),
                ('display_name', models.CharField(max_length=100, verbose_name="Ko'rinadigan nomi")),
                ('permissions', models.JSONField(default=list, verbose_name='Ruxsatlar')),
                ('is_system_role', models.BooleanField(default=False, help_text="Tizimiy rollar o'chirib bo'lmaydi")),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'historical Rol',
                'verbose_name_plural': 'historical Rollar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
