# Generated by Django 5.2.14 on 2026-05-16 00:30

import apps.commerce.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_single_device_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('billing_period', models.CharField(choices=[('monthly', 'Oylik'), ('yearly', 'Yillik'), ('lifetime', 'Butun umr')], max_length=10)),
                ('pricing_model', models.CharField(choices=[('flat', 'Belgilangan summa (org)'), ('per_seat', "O'quvchi soni bo'yicha")], max_length=10)),
                ('price_uzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Cheksiz uchun null', null=True)),
                ('features', models.JSONField(default=dict, help_text="Misol: {'ai_diagnostic': true, 'analytics': true}")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'price_uzs'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('stub', 'Stub (dev/test)')], db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('created', 'Yaratilgan'), ('processing', 'Ishlanmoqda'), ('succeeded', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan')], db_index=True, default='created', max_length=12)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coins_to_credit', models.PositiveIntegerField(help_text="Muvaffaqiyatli bo'lsa user wallet'iga shu Coin qo'shiladi")),
                ('provider_tx_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('target_subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='commerce.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Payment Intent',
                'verbose_name_plural': 'Payment Intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_reward', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invited', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joined_referral', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.commerce.models._gen_code, max_length=16, unique=True)),
                ('is_withdrawable', models.BooleanField(default=False, help_text='50+ referrals → naqd UZS yechib olish ochiladi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Code',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trial davri'), ('active', 'Faol'), ('past_due', "To'lov muddati o'tgan"), ('cancelled', 'Bekor qilingan'), ('expired', 'Muddati tugagan')], db_index=True, default='trialing', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_started_at', models.DateTimeField()),
                ('current_period_ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
                ('last_payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='commerce.paymentintent')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='commerce.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Organization Subscription',
                'verbose_name_plural': 'Organization Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_coins', models.PositiveIntegerField(default=0, verbose_name='Sertifikat Coin balansi')),
                ('pending_cash_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Affiliate withdraw'ga tayyor naqd UZS", max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('topup', "To'ldirish (Payme/Click)"), ('spend', 'Sarflash (premium feature)'), ('refund', 'Qaytarish'), ('referral_bonus', 'Referral bonus'), ('affiliate_payout', 'Affiliate cash-out (UZS)'), ('adjustment', 'Admin sozlash')], db_index=True, max_length=24)),
                ('coins_delta', models.IntegerField(default=0)),
                ('cash_uzs_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_after_coins', models.PositiveIntegerField()),
                ('balance_after_cash_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='commerce.paymentintent')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='commerce.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['user', '-created_at'], name='commerce_pa_user_id_b1bf22_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', '-created_at'], name='commerce_pa_status_c75766_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentintent',
            unique_together={('provider', 'provider_tx_id')},
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['organization', 'status'], name='commerce_or_organiz_825843_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status', 'current_period_ends_at'], name='commerce_or_status_3e4ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='commerce_wa_wallet__c5a1da_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['kind', '-created_at'], name='commerce_wa_kind_659fd9_idx'),
        ),
    ]
