# Generated by Django 5.2.14 on 2026-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_enable_rls'),
        ('organizations', '0002_organization_single_device_policy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(condition=models.Q(('auto_renew', True), ('status__in', ['active', 'trialing'])), fields=['current_period_ends_at'], name='sub_active_renewable_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'kind', '-created_at'], name='wt_wallet_kind_idx'),
        ),
    ]
