# Generated by Django 5.2.14 on 2026-05-15 22:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_enable_rls'),
        ('organizations', '0002_organization_single_device_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('submitted', 'Topshirilgan'), ('cancelled', 'Bekor qilingan'), ('disputed', "Shikoyat ko'rib chiqilmoqda"), ('expired', 'Vaqti tugagan')], db_index=True, default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='0.00 — 100.00', max_digits=6, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('heartbeat_last_at', models.DateTimeField(blank=True, null=True)),
                ('strikes', models.PositiveSmallIntegerField(default=0)),
                ('cancel_reason', models.CharField(blank=True, choices=[('tab_switch', "Tab o'zgartirish"), ('fullscreen_exit', 'Fullscreen chiqish'), ('heartbeat_lost', 'Aloqa uzilgan'), ('admin_cancelled', 'Admin tomonidan bekor')], max_length=24, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AntiCheatEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('tab_switch', "Tab o'zgartirish"), ('window_blur', 'Window blur'), ('fullscreen_exit', 'Fullscreen chiqish'), ('heartbeat_miss', "Heartbeat o'tkazib yuborilgan"), ('devtools_open', 'DevTools ochilgan'), ('copy_attempt', 'Nusxalash urinishi')], db_index=True, max_length=24)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Misol: {"user_agent": "...", "screen_w": 1920}')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_events', to='exams.examattempt')),
            ],
            options={
                'verbose_name': 'Anti-Cheat Event',
                'verbose_name_plural': 'Anti-Cheat Events',
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Davomiyligi (daqiqa)')),
                ('scheduled_at', models.DateTimeField(help_text="Yakshanba 10:00 (yoki B2B custom). Shu vaqtdan oldin attempt yaratib bo'lmaydi.", verbose_name='Boshlanish vaqti')),
                ('closes_at', models.DateTimeField(help_text="Shu vaqtdan keyin yangi attempt yaratib bo'lmaydi.", verbose_name='Yopilish vaqti')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', "E'lon qilingan"), ('closed', 'Yopilgan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='draft', max_length=16)),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text="True bo'lsa barcha tenantlar ko'radi (cross-tenant leaderboard).", verbose_name='Platform mock')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mock_exams', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Mock Exam',
                'verbose_name_plural': "Mock Exam'lar",
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='exams.mockexam'),
        ),
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='exams.mockexam')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_exam_links', to='catalog.questionversion')),
            ],
            options={
                'verbose_name': 'Mock Exam Question',
                'verbose_name_plural': 'Mock Exam Questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='mockexam',
            name='questions',
            field=models.ManyToManyField(related_name='mock_exams', through='exams.MockExamQuestion', to='catalog.questionversion'),
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blueprint', models.JSONField(help_text='Misol: [{"topic_id": "uuid", "count": 10, "difficulty": "hard"}]', verbose_name='Blueprint')),
                ('status', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('abandoned', 'Tashlab ketilgan')], db_index=True, default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Session',
                'verbose_name_plural': 'Practice Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionDispute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('wrong_answer', "To'g'ri javob yo'q"), ('image_broken', 'Rasm ochilmadi'), ('ambiguous', "Bir nechta to'g'ri javob bor"), ('typo', 'Imloda xato'), ('other', 'Boshqa')], db_index=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('quarantined', 'Karantin qilingan'), ('rejected', 'Rad etilgan')], db_index=True, default='open', max_length=16)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='exams.examattempt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='catalog.questionversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Dispute',
                'verbose_name_plural': 'Question Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected', models.JSONField(help_text="Format question type'ga bog'liq.", verbose_name='Tanlangan javob')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('auto_correct', models.BooleanField(default=False, verbose_name='Auto-correct (quarantine bonus)')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='catalog.questionversion')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.practicesession')),
            ],
            options={
                'verbose_name': 'User Answer',
                'verbose_name_plural': 'User Answers',
                'ordering': ['answered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'status'], name='exams_exama_user_id_120f19_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'status'], name='exams_exama_exam_id_39972c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('exam', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='mockexamquestion',
            unique_together={('mock_exam', 'order'), ('mock_exam', 'question_version')},
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['status', 'scheduled_at'], name='exams_mocke_status_e447e9_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['is_public', 'status'], name='exams_mocke_is_publ_4f1dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'status'], name='exams_pract_user_id_581660_idx'),
        ),
        migrations.AddIndex(
            model_name='questiondispute',
            index=models.Index(fields=['question_version', 'status'], name='exams_quest_questio_78931e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questiondispute',
            unique_together={('attempt', 'question_version', 'user')},
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'question_version'], name='exams_usera_attempt_36f4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['session', 'question_version'], name='exams_usera_session_f90e18_idx'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attempt__isnull', False), ('session__isnull', True)), models.Q(('attempt__isnull', True), ('session__isnull', False)), _connector='OR'), name='useranswer_attempt_xor_session'),
        ),
    ]
