# Generated by Django 5.2.14 on 2026-05-16 11:11

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examattempt_created_by_examattempt_updated_by'),
        ('organizations', '0003_historicalmembership_historicalorganization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExamAttempt',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pii_redacted', models.BooleanField(default=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('submitted', 'Topshirilgan'), ('cancelled', 'Bekor qilingan'), ('disputed', "Shikoyat ko'rib chiqilmoqda"), ('expired', 'Vaqti tugagan')], db_index=True, default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='0.00 — 100.00', max_digits=6, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('heartbeat_last_at', models.DateTimeField(blank=True, null=True)),
                ('strikes', models.PositiveSmallIntegerField(default=0)),
                ('cancel_reason', models.CharField(blank=True, choices=[('tab_switch', "Tab o'zgartirish"), ('fullscreen_exit', 'Fullscreen chiqish'), ('heartbeat_lost', 'Aloqa uzilgan'), ('admin_cancelled', 'Admin tomonidan bekor')], max_length=24, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.mockexam')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Tashkilot')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Exam Attempt',
                'verbose_name_plural': 'historical Exam Attempts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
