# Generated by Django 5.2.14 on 2026-05-16 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_questionversion_is_quarantined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Skill nomi')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Hierarchy: Math → Algebra → Linear equations', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='intelligence.skilltag')),
                ('questions', models.ManyToManyField(blank=True, related_name='skills', to='catalog.question')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='catalog.subject')),
            ],
            options={
                'verbose_name': 'Skill Tag',
                'verbose_name_plural': 'Skill Taglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alpha', models.PositiveIntegerField(default=1, help_text='Successes + 1')),
                ('beta', models.PositiveIntegerField(default=1, help_text='Failures + 1')),
                ('mastery', models.FloatField(db_index=True, default=0.5, help_text='alpha / (alpha+beta)')),
                ('confidence', models.FloatField(default=0.0, help_text='1 - sqrt(variance)')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='intelligence.skilltag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill Profile',
                'verbose_name_plural': 'User Skill Profiles',
                'ordering': ['mastery'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('ready', 'Tayyor'), ('failed', 'Xato')], db_index=True, default='pending', max_length=8)),
                ('summary', models.JSONField(default=dict, help_text='{"weak": [...], "strong": [...], "stats": {...}}')),
                ('content', models.TextField(blank=True, help_text='LLM dan kelgan motivatsion matn')),
                ('error', models.TextField(blank=True)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Feedback',
                'verbose_name_plural': 'AI Feedbacks',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='intelligenc_user_id_581a00_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpenEndedSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('essay', 'Insho (matn)'), ('audio', 'Ovozli javob')], max_length=8)),
                ('content', models.TextField(blank=True, help_text='Insho matni yoki audio transcript')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='openended/audio/')),
                ('status', models.CharField(choices=[('pending', 'AI tahlil kutilmoqda'), ('ai_reviewed', 'AI baholangan'), ('human_approved', 'Inson tasdiqlagan'), ('disputed', "Bahsli (admin ko'radi)"), ('failed', 'AI xato')], db_index=True, default='pending', max_length=16)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.JSONField(default=dict, help_text='{"grammar": 80, "content": 70, "structure": 90, "rationale": "..."}')),
                ('human_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('human_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ai_completed_at', models.DateTimeField(blank=True, null=True)),
                ('human_completed_at', models.DateTimeField(blank=True, null=True)),
                ('human_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openended_reviews', to=settings.AUTH_USER_MODEL)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openended_submissions', to='catalog.questionversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openended_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Open-Ended Submission',
                'verbose_name_plural': 'Open-Ended Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='intelligenc_status_b10e60_idx'), models.Index(fields=['user', '-submitted_at'], name='intelligenc_user_id_73ea2c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='skilltag',
            index=models.Index(fields=['parent'], name='intelligenc_parent__7b3bea_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltag',
            index=models.Index(fields=['subject'], name='intelligenc_subject_6aaf09_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillprofile',
            index=models.Index(fields=['user', 'mastery'], name='intelligenc_user_id_ac0f11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userskillprofile',
            unique_together={('user', 'skill')},
        ),
    ]
