# Generated by Django 5.2.14 on 2026-05-16 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_single_device_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_attempt_id', models.UUIDField(db_index=True)),
                ('mock_exam_id', models.UUIDField(db_index=True)),
                ('subject_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('correct_count', models.PositiveIntegerField()),
                ('total_count', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('region_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Event',
                'verbose_name_plural': 'Exam Events',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['organization', 'subject_id', '-completed_at'], name='analytics_e_organiz_2a4b4d_idx'), models.Index(fields=['organization', '-completed_at'], name='analytics_e_organiz_c4eca6_idx'), models.Index(fields=['organization', 'user', '-completed_at'], name='analytics_e_organiz_a5662e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(help_text="Misol: 'students_full', 'subject_breakdown', 'weekly_trend'", max_length=32)),
                ('fmt', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel (.xlsx)')], default='csv', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Ishlanmoqda'), ('ready', 'Tayyor'), ('failed', 'Xato')], db_index=True, default='pending', max_length=12)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('error', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Tashkilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['organization', '-requested_at'], name='analytics_r_organiz_be0453_idx')],
            },
        ),
    ]
