# Generated by Django 5.2.14 on 2026-05-16 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('exception', models.CharField(max_length=255)),
                ('traceback', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reprocessed_at', models.DateTimeField(blank=True, null=True)),
                ('reprocessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Failed Task (DLQ)',
                'verbose_name_plural': 'Failed Tasks (DLQ)',
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['task_name', '-failed_at'], name='analytics_f_task_na_416381_idx')],
            },
        ),
    ]
