# Generated by Django 5.2.14 on 2026-05-16 11:11

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='+998901234567 formatida', max_length=20, null=True, verbose_name='Telefon raqami')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('telegram_language', models.CharField(blank=True, max_length=10, null=True)),
                ('tg_linked_at', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.TextField(blank=True, max_length=100, null=True)),
                ('preferred_lang', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5, verbose_name='Til')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Tug'ilgan yil")),
                ('study_year', models.CharField(blank=True, choices=[('grade_10', '10-sinf'), ('grade_11', '11-sinf'), ('graduate', 'Bitiruvchi'), ('university', 'Talaba'), ('teacher', "O'qituvchi"), ('other', 'Boshqa')], max_length=20, null=True, verbose_name="O'qish bosqichi")),
                ('target_score', models.PositiveSmallIntegerField(blank=True, help_text='Maksimal 189', null=True, verbose_name='Maqsad ball (DTM)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('district', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.district', verbose_name='Tuman')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'historical Foydalanuvchi',
                'verbose_name_plural': 'historical Foydalanuvchilar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
