# Generated by Django 5.2.14 on 2026-05-15 23:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], db_index=True, max_length=8)),
                ('period_key', models.CharField(db_index=True, help_text='Misol: "2026-W19" (weekly), "2026-05" (monthly), "2026" (yearly)', max_length=16)),
                ('scope_kind', models.CharField(choices=[('global', 'Platforma (global)'), ('region', 'Viloyat'), ('tenant', 'Tashkilot'), ('mock', 'Mock imtihon')], db_index=True, max_length=8)),
                ('scope_id', models.CharField(blank=True, default='', help_text="global scope uchun bo'sh; boshqalar uchun region_id/org_id/mock_id", max_length=64)),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('entries', models.JSONField(default=list, help_text='Top-N: [{"user_id": "uuid", "score": float, "rank": int}, ...]')),
            ],
            options={
                'verbose_name': 'Leaderboard Snapshot',
                'verbose_name_plural': 'Leaderboard Snapshots',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['period', 'scope_kind', 'period_key'], name='engagement__period_42bde0_idx')],
                'unique_together': {('period', 'period_key', 'scope_kind', 'scope_id')},
            },
        ),
    ]
