# Generated by Django 5.2.14 on 2026-05-16 01:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('rank_order', models.PositiveSmallIntegerField(help_text='1=Bronza, 2=Kumush, 3=Oltin, 4=Olmos', unique=True)),
                ('color_hex', models.CharField(default='#888888', max_length=7)),
                ('promote_reward_coins', models.PositiveIntegerField(default=100, help_text="Bu liga'ga ko'tarilgan user'ga beriladigan Coin")),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'ordering': ['rank_order'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
            },
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('rank_in_league', models.PositiveIntegerField(blank=True, null=True)),
                ('promoted', models.BooleanField(default=False)),
                ('demoted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='engagement.league')),
                ('next_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='engagement.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'League Membership',
                'verbose_name_plural': 'League Memberships',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['league', 'period_start', '-points_earned'], name='engagement__league__c9f969_idx')],
                'unique_together': {('user', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram bot'), ('push', 'Push notification'), ('sms', 'SMS PlayMobile'), ('in_app', 'In-app feed')], db_index=True, help_text='Yo IN_APP (har doim) yo external channel actual delivery', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Past'), ('normal', 'Oddiy'), ('important', 'Muhim'), ('urgent', 'Shoshilinch')], db_index=True, default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', "Jo'natilgan"), ('failed', 'Xato'), ('read', "O'qilgan")], db_index=True, default='pending', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='engagement__user_id_270c05_idx'), models.Index(fields=['status', 'priority'], name='engagement__status_98f045_idx')],
            },
        ),
    ]
