# Generated by Django 5.2.14 on 2026-05-16 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_league_userstreak_leaguemembership_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_rows', to='engagement.leaderboardsnapshot')),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['snapshot', 'rank'],
                'indexes': [models.Index(fields=['snapshot', 'rank'], name='engagement__snapsho_15f537_idx'), models.Index(fields=['user_id', '-snapshot'], name='engagement__user_id_8f06d1_idx')],
                'unique_together': {('snapshot', 'user_id')},
            },
        ),
    ]
